### ISSUE TITLE
Add some example parses of very complex sentences by the tested systems.

### ISSUE THREAD

**Issue by logicReasoner** [flipz357/amr-metric-suite#1]
Hello,  @flipz357 
I appreciate your work in comparing the SOTA systems that can do AMR parsing. 
My request: In the `examples` directory, can you provide a comparison of how well each system performs on some very complex example sentences. 
For example, I'd like to see the resulting parses of the following sentence taken from WikiPedia: `A computer is a machine that accepts data as input, processes that data using programs, and outputs the processed data as information.`

BTW, I tried to get `AMR-gs` (which seems to be missing from your comparison list) to work on my computer following your advice here: https://github.com/jcyk/AMR-gs/issues/5
but I failed due to not having a modern NVIDIA GPU. So before I purchase such an expensive device, I'd appreciate seeing the above examples in order to decide if the purchase is really worth it for my use case. 

 Thanks in advance and keep up the good work! :)

**Comment by flipz357** [comment]
Hi @logicReasoner ,

thanks for the interest in this work. And good that you have reminded me to update the score table in with the latest parser (done). I also parsed your sentence, which is indeed quite complex, with the no-recat version of AMR-gs.

Here's the result:

```
# ::id 0
# ::snt A computer is a machine that accepts data as input, processes that data using programs, and outputs the processed data as information.
# ::tokens ["A", "computer", "is", "a", "machine", "that", "accepts", "data", "as", "input", ",", "processes", "that", "data", "using", "programs", ",", "and", "outputs", "the", "processed", "data", "as", "information", "."]
# ::lemmas ["a", "computer", "be", "a", "machine", "that", "accept", "datum", "as", "input", ",", "process", "that", "datum", "use", "program", ",", "and", "output", "the", "process", "datum", "as", "information", "."]
# ::pos_tags ["DT", "NN", "VBZ", "DT", "NN", "WDT", "VBZ", "NNS", "IN", "NN", ",", "NNS", "WDT", "NNS", "VBG", "NNS", ",", "CC", "NNS", "DT", "VBN", "NNS", "IN", "NN", "."]
# ::ner_tags ["O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]
(c0 / machine
      :ARG0-of (c1 / process-01
            :ARG1 (c4 / data
                  :mod (c9 / that))
            :manner (c5 / use-01
                  :ARG1 (c10 / program)))
      :ARG0-of (c2 / output
            :ARG1 (c6 / data
                  :ARG1-of (c11 / process-01))
            :manner (c7 / information))
      :ARG0-of (c3 / accept-01
            :ARG1 (c8 / thing)))
```

Good:

- it captures that there is a machine which does three things: 
    - processing, 
    - outputing 
    - and accepting.
- it captures that the data is processed using programs (":manner use program")

Not so good:

- that the machine accepts a "thing" is true, but it is left underspecified (thing should rather be "input/data").
- ideally (c11 / process) should be replaced with a coreference to (c1 / process) to indicate that it is the same process.
- "computer", is missing, unfortunately
- etc.

Some things you'd like to have but I believe that they are not captured by AMR theory in general (e.g., there is a temporal ordering, 1. accepting 2. processing, 3. output).

Summary:

I'd say that it can capture the core meaning of this complex sentence to a good extent, but there are some flaws.

**Comment by logicReasoner** [comment]
Thanks for the quick and elaborate analysis. This is exactly what I was looking for.

I agree with your summary. It seems like we still have a long way to go with AMR parsing.
Out of curiosity, I wonder how GTP-3 would perform here after having been trained on such a task. Of course, it's a closed source product so we'll never really know. :(
